// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class PruebavisitanteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pruebavisitante() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.linkText("Regístrate")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("nombre")).click();
    driver.findElement(By.id("nombre")).sendKeys("Javier fernandez");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123456");
    {
      WebElement element = driver.findElement(By.id("rol"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("rol"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("rol"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("rol")).click();
    driver.findElement(By.cssSelector("option:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123456");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Mi perfil")).click();
    driver.findElement(By.linkText("🎯 Obtener recomendaciones personalizadas")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .card .btn-success")).click();
    driver.findElement(By.linkText("Leer")).click();
    driver.findElement(By.linkText("📄 Descargar PDF")).click();
    driver.findElement(By.linkText("← Volver al catálogo")).click();
    driver.findElement(By.linkText("Leer")).click();
    driver.findElement(By.linkText("← Volver al catálogo")).click();
    driver.findElement(By.linkText("Mi perfil")).click();
    driver.findElement(By.cssSelector("button")).click();
  }
}
