// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class PruebaEscritorTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pruebaEscritor() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.linkText("Regístrate")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("pabloJC@gmail.com");
    driver.findElement(By.id("nombre")).click();
    driver.findElement(By.id("nombre")).sendKeys("pablo");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("12345");
    {
      WebElement element = driver.findElement(By.id("rol"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("rol"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("rol"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("rol")).click();
    {
      WebElement dropdown = driver.findElement(By.id("rol"));
      dropdown.findElement(By.xpath("//option[. = 'Escribir']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("pabloJC@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("12345");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("titular")).click();
    driver.findElement(By.id("titular")).sendKeys("Pablo jimenez cano");
    driver.findElement(By.id("infoBancaria")).click();
    driver.findElement(By.id("infoBancaria")).sendKeys("ES7832r7969848795");
    driver.findElement(By.id("infoBancaria")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("infoBancaria")).sendKeys("ES78327969848795");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Cerrar sesión")).click();
    driver.findElement(By.linkText("Iniciar sesión")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("pabloJC@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("12345");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Mi perfil")).click();
    driver.findElement(By.linkText("📚 Mis resúmenes")).click();
    driver.findElement(By.linkText("Subir nuevo resumen")).click();
    driver.findElement(By.id("titulo")).click();
    driver.findElement(By.id("titulo")).sendKeys("Freakonomics");
    driver.findElement(By.id("autorOriginal")).click();
    driver.findElement(By.id("autorOriginal")).sendKeys("Steven D. Levitt");
    {
      WebElement element = driver.findElement(By.id("categoria"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("categoria"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("categoria"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("categoria")).click();
    {
      WebElement dropdown = driver.findElement(By.id("categoria"));
      dropdown.findElement(By.xpath("//option[. = 'Economía']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(3)")).click();
    driver.findElement(By.id("pdfFile")).click();
    driver.findElement(By.id("pdfFile")).sendKeys("C:\\fakepath\\pruebaprueba.pdf");
    driver.findElement(By.id("audioFile")).click();
    driver.findElement(By.id("audioFile")).sendKeys("C:\\fakepath\\sample-15s.mp3");
    driver.findElement(By.cssSelector(".actions > input")).click();
    driver.findElement(By.linkText("Editar")).click();
    driver.findElement(By.id("autorOriginal")).click();
    driver.findElement(By.id("autorOriginal")).sendKeys("Steven D. Levitt y Stephen J. Dubner");
    driver.findElement(By.cssSelector(".actions > input")).click();
    driver.findElement(By.linkText("Catálogo")).click();
    {
      WebElement element = driver.findElement(By.id("categoria"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("categoria"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("categoria"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("categoria")).click();
    {
      WebElement dropdown = driver.findElement(By.id("categoria"));
      dropdown.findElement(By.xpath("//option[. = 'Economía']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) .btn")).click();
    driver.findElement(By.id("puntuacion")).click();
    {
      WebElement dropdown = driver.findElement(By.id("puntuacion"));
      dropdown.findElement(By.xpath("//option[. = '5']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(5)")).click();
    driver.findElement(By.id("comentario")).click();
    driver.findElement(By.id("comentario")).sendKeys("El mejor de todos");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("← Volver al catálogo")).click();
    driver.findElement(By.linkText("Mi perfil")).click();
    driver.findElement(By.linkText("📚 Mis resúmenes")).click();
    driver.findElement(By.cssSelector("form > .btn-outline")).click();
    assertThat(driver.switchTo().alert().getText(), is("¿Seguro que quieres borrar este resumen?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.linkText("Catálogo")).click();
    {
      WebElement element = driver.findElement(By.id("categoria"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("categoria"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("categoria"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("categoria")).click();
    {
      WebElement dropdown = driver.findElement(By.id("categoria"));
      dropdown.findElement(By.xpath("//option[. = 'Economía']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
    driver.findElement(By.linkText("Mi perfil")).click();
    driver.findElement(By.cssSelector("button:nth-child(1)")).click();
  }
}
