// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class PruebaLectorTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pruebaLector() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.linkText("Regístrate")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("santiago@gmail.com");
    driver.findElement(By.id("nombre")).click();
    driver.findElement(By.id("nombre")).sendKeys("santiago ciriza");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("1234567");
    driver.findElement(By.id("rol")).click();
    {
      WebElement dropdown = driver.findElement(By.id("rol"));
      dropdown.findElement(By.xpath("//option[. = 'Escribir']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id("rol"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("rol"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("rol"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("rol")).click();
    {
      WebElement dropdown = driver.findElement(By.id("rol"));
      dropdown.findElement(By.xpath("//option[. = 'Leer']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("santiago@gmail.com");
    driver.findElement(By.id("password")).sendKeys("1234567");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Mi perfil")).click();
    driver.findElement(By.linkText("💳 Suscribirse como LECTOR")).click();
    driver.findElement(By.id("titular")).click();
    driver.findElement(By.id("titular")).sendKeys("Santiago Ciriza");
    driver.findElement(By.id("infoBancaria")).sendKeys("ES1236435329");
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    driver.findElement(By.linkText("Cerrar sesión")).click();
    driver.findElement(By.linkText("Iniciar sesión")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("santiago@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("1234567");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Mi perfil")).click();
    driver.findElement(By.linkText("Catálogo")).click();
    driver.findElement(By.cssSelector("tr:nth-child(14) .btn")).click();
    driver.findElement(By.linkText("📄 Descargar PDF")).click();
    driver.findElement(By.id("puntuacion")).click();
    {
      WebElement dropdown = driver.findElement(By.id("puntuacion"));
      dropdown.findElement(By.xpath("//option[. = '4']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(4)")).click();
    driver.findElement(By.id("comentario")).click();
    driver.findElement(By.id("comentario")).sendKeys("Muy buen libro");
    driver.findElement(By.cssSelector("button:nth-child(4)")).click();
    driver.findElement(By.linkText("← Volver al catálogo")).click();
    driver.findElement(By.cssSelector("tr:nth-child(12) .btn")).click();
    driver.findElement(By.cssSelector("form > .btn")).click();
    driver.findElement(By.linkText("← Volver al catálogo")).click();
    driver.findElement(By.linkText("Ver favoritos")).click();
    driver.findElement(By.linkText("Limpiar")).click();
    driver.findElement(By.linkText("Mi perfil")).click();
    driver.findElement(By.linkText("🎯 Obtener recomendaciones personalizadas")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) .btn-success")).click();
    driver.findElement(By.linkText("Mi perfil")).click();
    driver.findElement(By.cssSelector(".btn-subscripcion:nth-child(2)")).click();
  }
}
